### PR TITLE
Fix Markdown formatting

### PR DESCRIPTION
**Pull request by szarnyasg**
Headers are broken due to [GitHub moving to a different Markdown parser](https://github.com/github/markup/issues/1013). Fixed them in this PR.

### CODE REVIEW

**Comment by szarnyasg** [comment]
How do I sign a CLA?

**Comment by Nemikolh** [comment]
Thanks for your pull request! :tada: 

> How do I sign a CLA?

I would say that this part of the `CONTRIBUTING.md` needs to be updated. We no longer require a CLA (@alzindiq please feel free to correct me here).

I am planning to give a fresh update to this repository in a few weeks. If you are interested on doing more contributions, feel free to open an issue about some aspect you are interested on improving. There's still a lot to do! :)

**Comment by szarnyasg** [comment]
Thanks for merging this! I am working on an openCypher-related project, [ingraph](https://github.com/FTSRG/ingraph) that has an openCypher-to-relational-algebra compiler and uses the Catalyst module of Apache Spark to represent the relational algebra tree. I figures that mapping a Catalyst tree to SQL should be relatively straightforward. Of course, after digging a bit more into the subject, I realized that this is not the case -- both a schema for the graph and for the relational database, and also their mapping is required. gTop seems a good pick for this use case. Will your upcoming changes effect gTop or are do they work towards enhancing PathFinder and the cypher2sql compiler?

**Comment by MarcoLotz** [comment]
Szia @szarnyasg Thanks for the pull request 👍 

Your project looks really interesting! Indeed the (relational) gTop would likely solve that mapping problem for you. On my side, there will be no modifications that would change the gTop or the PathFinder module behaviour/interface. If there is any modification on those modules, it would likely be code cleanup and typos. @Nemikolh can say more on the cypher2sql compiler.

If you have modification proposals/requirements, just send us a pull request 😃

**Comment by szarnyasg** [comment]
Hey @Nemikolh do you have any roadmap for developing Cytosm in the future?

Our [ingraph project](https://github.com/FTSRG/ingraph) now has an openCypher to relational algebra compiler which supports most openCypher expressions with a few exceptions (paths, list comprehensions and pattern comprehensions, etc.). 

I believe that having a compiler greatly simplifies the mapping from oC to SQL. Our compiler can be easily extracted from ingraph, but it's not exactly lightweight: it's written in Scala and has a few additional dependencies: the Xtext parser and Apache Spark's Catalyst framework.

(Please feel free to contact me by email/Twitter DMs.)

**Comment by MarcoLotz** [comment]
Szia @szarnyasg good to know that ingraph project is going forward! Well done!

Currently the other core members and me are focusing on other cytosm-unrelated activities. So there's no planned road map on our side I'm afraid. Cytosm is a community-driven project, so contributions and proposals are always welcome.

For the items that your relational algebra compiler doesn't support yet, you may want to have a look in the Cytosm's PathFinder module - it will solve all bounded paths/patterns for you. All you need to do is write an input format for it.

If you need any further direction, feel free to ping me with a Twitter DM :)

**Pull request merged**
